markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: http://coolawk.com
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 鱼罗罗
    email: yujianrong_bupt@163.com
    imageLink: http://tp2.sinaimg.cn/1952891925/180/12345/1
    simpleIntro: 大家好，我是鱼罗罗
    detailIntro:
      <p>最近在找工作，在这里做个记录。</p>
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages服务的后台引擎。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/b291102
  - class: icon-github-alt
    url: http://github.com/yjrhot

#Links
customLinks:
  - item:
    - text: 掌心
      url: http://www.zhanxin.info
    - text: Jekyll
      url: http://jekyllrb.com
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-51713950-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: zhanxin